name: Deploy to Koyeb

on:
  pull_request:

  push:
    branches:
      - main
    paths:
      - src/**

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install & configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"

      - name: Create JWT secret
        uses: koyeb/action-git-deploy/secret@v1
        with:
          secret-name: JWT_SECRET
          secret-value: "${{ secrets.JWT_SECRET }}"

      - name: Create MongoDB password secret
        uses: koyeb/action-git-deploy/secret@v1
        with:
          secret-name: MONGO_PASSWORD
          secret-value: "${{ secrets.MONGO_PASSWORD }}"

      - name: Build & deploy the API to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: ianthea
          git-builder: docker
          git-docker-dockerfile: Dockerfile
          service-name: ianthea
          service-env: JWTSecret=@JWT_SECRET,mongoPassword=@MONGO_PASSWORD
          service-ports: "8000:http"
          service-regions: was
          service-routes: "/:8000"
          service-instance-type: free
